apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: oath2-proxy
name: oauth2-proxy
repo: https://oauth2-proxy.github.io/manifests
version: "7.12.0"
releaseName: oath2-proxy
namespace: oath2-proxy
valuesFile: values.yaml
