apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: oauth2-proxy
name: oauth2-proxy
repo: https://oauth2-proxy.github.io/manifests
version: "10.6.0"
releaseName: oauth2-proxy
namespace: oauth2-proxy
valuesFile: values.yaml
