apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: oauth2-proxy-secret
spec:
    secretTemplates:
        - name: oauth2-proxy-secret
          data:
            client-id: ENC[AES256_GCM,data:bDzqGVnyZ2VYod2NKrA1wowvX6g=,iv:Sj34/RSo8yslNiJ47IdW4SF3cqXJrk7+xoVOLLKiFUM=,tag:Lhw6/XiihLp/dsmipVofEA==,type:str]
            client-secret: ENC[AES256_GCM,data:EPLmQ1ATYCYiLA1DCg/ZsSktCYdILL/oB+cLIJhT32d8v/3UU8Odjw==,iv:nbcSMWhog0ToyE5K3OOXZw9WOyrNusKbAJTwxKdZKCI=,tag:rc9+/6gMSNGdhqm9PDTNOQ==,type:str]
            cookie-secret: ENC[AES256_GCM,data:wghPjSzlQL4jwz/DrFHTdEHiyPNU6KkmlvcCJpPY4Pzulootb75Jq0unKVU=,iv:j5ouXwVAJ2mYV23S8JFFraEoDk1pUOP7oIVCk2hFTZ8=,tag:vDcagmN2Irfh4ygU5hNMLg==,type:str]
          stringData:
            config-file: ENC[AES256_GCM,data:vqrOMKdSUJDW74+65vHtUhRET/qsJ18kCCLLxtEO79ZAmiFKXssLOmJBbLtnrGGf/EuL2w+kQrxwTtqXblOZvCywbFKRWyDoBLu1P5qWBCAhrtuu39tRuTUCGmXs9yJScIDq4FZ39iLkSIDCRzz1aVQwjHB7eDkJ6IEdBsUb1bstYXond3xos5Mi7sktss9ZVpgqqK9osV/HlEqU9VhvSETOQQSad1Jn+zfarbGMaHeSw+ryUdOG0a+v2t+CvdPUC5ZPT8zRwJg=,iv:vAGn17g6vqLMMxk3+vlq/Bslw2YVt3tnOeF1LgsCfM0=,tag:vhlSUJ9WwYvFKZV1lKqHpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2w287dk7fgqd2srhzvgguqy3a9ft4q687sqqr5lva0sxdy0pseqdj23qw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1czdvc2FUU0dHaVllWGRx
            Znk4N0dFc3JWV3lwREZjemtQSW1IcVcxbldnClJ3SmhHa0hjd0dlbmdtTFYrNFFC
            QnpSZW4vZTVyWS9ya1hYNys0T0YxRkkKLS0tIElndUxlOXV6SmE3dUh0UStKK2dF
            NllxOVJnYzhTQStadVI0MmZTSjFBd3cKBw7f9N7ULADRzhw43DRxYLuggA/pj9tf
            ic36Gugjz2XO9nHsYwzjTZSZYb/ALamgUaAE+4ElRrU+5uoh0OLHoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T15:53:41Z"
    mac: ENC[AES256_GCM,data:vqX1e821LVgd0Xg/zdJdMO8Wn+xE9b+nssEnBI1SC80CVTwfGYbEVp1822RG5sn5teKE+vt5yDM5qJiHBFw1/XLXZkOozRbkZAki6X7zzmfaeZGa5oG+Qo8SDlgFxuT9NVMCGLLDBXUa3qmbJwQu8n0Fj63dNfj7M+mqHNkF6V4=,iv:CDpQu+NfxrqrkUJJ9DG6IC0Fe+yNvbs0W7l1pgfDwJk=,tag:sLY9DXDh6Q1VZ+/VOPxwsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
