config:
  existingSecret: oauth2-proxy-secret
ingress:
  enabled: true
  path: /
  hosts:
    - auth.davidconalrobinson.com
  annotations:
    kubernetes.io/ingress.class: nginx
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: auth.davidconalrobinson.com
  tls:
    - secretName: letsencrypt-prod
      hosts:
        - auth.davidconalrobinson.com
