apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sops-secrets-operator
resources:
- https://raw.githubusercontent.com/isindir/sops-secrets-operator/0.14.3/config/crd/bases/isindir.github.com_sopssecrets.yaml
generators:
- chart.yaml
