annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added ability to configure `imagePullSecrets` via helm `global` value."
    - kind: added
      description: "Added options to configure `labelFilter` and `managedRecordTypes` via dedicated helm values."
    - kind: changed
      description: "Allow templating `serviceaccount.annotations` keys and values, by rendering them using the `tpl` built-in function."
    - kind: changed
      description: "Updated _ExternalDNS_ OCI image version to [v0.15.1](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.15.1)."
    - kind: fixed
      description: "Fixed automatic addition of pod selector labels to `affinity` and `topologySpreadConstraints` if not defined."
    - kind: fixed
      description: "Fixed missing Ingress permissions when using Istio sources."
apiVersion: v2
appVersion: 0.15.1
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
keywords:
- kubernetes
- externaldns
- external-dns
- dns
- service
- ingress
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.15.1
