apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: external-dns
name: external-dns
repo: https://kubernetes-sigs.github.io/external-dns
version: "1.15.1"
releaseName: external-dns
namespace: external-dns
valuesFile: values.yaml
