apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager
name: cert-manager
repo: https://charts.jetstack.io
version: "1.17.0"
releaseName: cert-manager
namespace: cert-manager
valuesFile: values.yaml
